# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vectorSubset <- function(x, i) {
    .Call('BEDMatrix_vectorSubset', PACKAGE = 'BEDMatrix', x, i)
}

matrixSubset <- function(x, i, j) {
    .Call('BEDMatrix_matrixSubset', PACKAGE = 'BEDMatrix', x, i, j)
}

