# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subsetBED <- function(path, n, p, i, j) {
    .Call('BEDMatrix_subsetBED', PACKAGE = 'BEDMatrix', path, n, p, i, j)
}

